### ISSUE TITLE
New gesture for copying URL to clipboard

### ISSUE THREAD

**Issue by piotrkustal** [smoothgesturesplus/Issues#33]
Hi,

we already do have gesture for opening url in new tab/window that's obvious, but it would be awesome to introduce new gesture for copying URL location into a clipboard. So for example we could highlight few or single URLs first and then use gesture to copy them all into clipboard.

Thank you in advance.

**Comment by smoothgesturesplus** [comment]
This was added back in February. Let me know if you have any issues with it. Thanks!
