### ISSUE TITLE
Undo Close Tab action does not work

### ISSUE THREAD

**Issue by zommerfelds** [smoothgesturesplus/Issues#35]
Hi, when I perform the Undo Close Tab action nothing happens. The keyboard shortcut works (Ctrl+Shift+T). Other actions seem to be working fine. My system is Arch Linux with Chrome Version 44.0.2403.155 (64-bit).
Let me know if I can get you any more information.

**Comment by smoothgesturesplus** [comment]
A fix will be included in the next version.

**Comment by FatherOfAlways** [comment]
If possible, I would like to reopen this issue. This feature used to work for me until a few months ago but now doesn't any more. Sometimes it reopens tabs a tab that was NOT the last closed tab, while other times it does nothing.
If unable to replicate, I can spend some time to try and see if I can discern any patterns, though so far I have not.
