### ISSUE TITLE
Gesture cancellation

### ISSUE THREAD

**Issue by koreabell** [smoothgesturesplus/Issues#36]
Gesture extension I used with the firefox had this gesture "cancellation" feature where if you do a gesture and you have changed your mind (especially the close tab gesture), instead of doing random additional gestures then releasing the right mouse button, you hold your mouse (with RMB pressed) for a brief moment (something like 2-3 seconds) and it cancels the gesture and nothing happens after you release your right mouse button. I really would like this feature to be added.

**Comment by smoothgesturesplus** [comment]
This has been requested in the past. It may yet be added, but in the meantime you should know that SGPlus uses a unique cancellation feature that cancels when no valid gesture can be created. So, just shake your mouse and don't waste those 3 seconds waiting.

Duplicate #6
