### ISSUE TITLE
where is "next tab" in tab management?

### ISSUE THREAD

**Issue by martinec1** [smoothgesturesplus/Issues#37]
Hi, I set rightclick+scroll up to move to previous tab in chrome. However, I tried to set rightclick+scroll down to move to next tab in chrome, however, no "next tab" command is shown among those I can choose from. Can you fix it please? Thanks, Martin

**Comment by smoothgesturesplus** [comment]
Scroll down. It is under 'More Available Actions'

**Comment by martinec1** [comment]
Sorry not found, there is not even any "More Available Actions", please
find print screen attached:

[image: Inline image 1]

S pozdravom / Best regards,

*JUDr. Martin BORŽÍK, LL.M.*
Jamnického 12
841 05 Bratislava
Slovenská republika/Slovak Republic

E-mail:    martin.borzik@gmail.com
Tel:         +421 915 995846

**Comment by smoothgesturesplus** [comment]
The image is not visible.

**Comment by martinec1** [comment]
attaching again as png:)

I have finally found more available actions (main menu), but no move to
"Next tab" is shown.

S pozdravom / Best regards,

*JUDr. Martin BORŽÍK, LL.M.*
Jamnického 12
841 05 Bratislava
Slovenská republika/Slovak Republic

E-mail:    martin.borzik@gmail.com
Tel:         +421 915 995846
