### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by appelsson** [smoothgesturesplus/Issues#38]
I have the latest Smooth Gestures (2.0) from the store.
Today I get a popup everytime when I try to draw a gesture:

smooth gestures PLUS needs to be Updated
To update smooth gestures PLUS:
Open the Extensions Page
Checkmark "Developer Mode"
Click "Update Extensions Now"

But this is the latest release. 
Removed, reinstalled the extension, but problem still exists and it's not working now.

**Comment by bbleeker** [comment]
I have the same problem.

**Comment by MeszesKPT** [comment]
Same issue here, can't use the extension this way.

**Comment by want2die** [comment]
update and not working. same problem. please fix this

**Comment by guasek** [comment]
:+1:

**Comment by klip** [comment]
Same for me

**Comment by want2die** [comment]
the issue is resolved by itself
