### ISSUE TITLE
Cursor jumps on some websites for right click

### ISSUE THREAD

**Issue by shdwjk** [smoothgesturesplus/Issues#39]
### Platform
OS X Yosemite 10.10.5
MacBook Pro (Retina, 15-inch, Mid 2014)
Google Chrome	47.0.2526.111 (Official Build) (64-bit)

Related: https://github.com/smoothgesturesplus/Issues/issues/20

### Description
On some websites (most notably https://app.roll20.net/forum/ ) right click and release to access the context menu causes the mouse to move right a bunch and up a bit, then deliver the right click.  When on the rightmost screen, this causes the event to be lost on the edge, when on B in [A][B][C][D], it causes the right click to be passed to about the middle of D.  Disabling the extension disables this behavior.  Profiling the website at the time shows an event is occurring inside gestures.js at the time of the right click.

I'm happy to help with whatever debugging you need.

**Comment by smoothgesturesplus** [comment]
This is a bug related to the Extras. To avoid the error for now you can
open the Extras app and click uninstall. However, you will need to double
right click for the context menu until a real fix is determined.

**Comment by shdwjk** [comment]
Ok, I did some digging with the help of a bit of syslog-ing.  The problem only happens on tabs where chrome is zoomed and seems to only be a problem when the zoom is <100%.  Probably on a right click event the javascript needs to consult tab.getZoom() and make adjustments before calling the Extras app. Based on my tests, it seems like the coordinates are doubled when zoom is <100%.

#### Example events:
###### Un-zoomed Event on monitor D of [A][B][C][D]
```
sgplus-extras.py[74350]: SmoothGesturesExtras: processRequest() - sending click :: {"click": {"y": -331, "x": 4726, "b": 2}}
```
###### 75% Zoomed Event on monitor D of [A][B][C][D] (approximately same location on screen (not page))
```
sgplus-extras.py[74350]: SmoothGesturesExtras: processRequest() - sending click :: {"click": {"y": -759, "x": 9377, "b": 2}}
```
###### 25% Zoomed Event on monitor D of [A][B][C][D] (approximately same location on screen (not page))
```
sgplus-extras.py[74350]: SmoothGesturesExtras: processRequest() - sending click :: {"click": {"y": -758, "x": 9375, "b": 2}}
```
###### 125% Zoomed Event on monitor D of [A][B][C][D] (approximately same location on screen (not page))
```
sgplus-extras.py[74350]: SmoothGesturesExtras: processRequest() - sending click :: {"click": {"y": -331, "x": 4726, "b": 2}}
```
###### 500% Zoomed Event on monitor D of [A][B][C][D] (approximately same location on screen (not page))
```
sgplus-extras.py[74350]: SmoothGesturesExtras: processRequest() - sending click :: {"click": {"y": -331, "x": 4726, "b": 2}}
```

**Comment by shdwjk** [comment]
Any thoughts on this?

**Comment by smoothgesturesplus** [comment]
It looks like this is probably caused by either (1) a bug in chrome when using your monitor layout or (2) your monitor layout is causing a side effect in the mitigation a different bug.

Can you duplicate the same monitor and window layout as above? Then open DevTools on a page and send me the content returned by these in-page variables:
* window.screenLeft
* window.screenTop

**Comment by smoothgesturesplus** [comment]
I have figured out you to recreate this issue and have developed a fix for it. Keep an eye out for an update to the extension and let me know if it fixed it for you!

**Comment by shdwjk** [comment]
Fantastic!  I can't wait!!

**Comment by shdwjk** [comment]
In fact, it looks like I've gotten the fix already as it's now working **_perfectly_**!

**Comment by vicliu1990** [comment]
it also happened on OS X 10.11.4 Beta (15E49a)
