### ISSUE TITLE
CTRL + F   feature?

### ISSUE THREAD

**Issue by mochakaboom** [smoothgesturesplus/Issues#41]
I don't think this is in the option but I use it for school a lot.  Would like to have a Smooth Gesture for CTRL + F   along with another gesture in order to move to the next/previous word with the quickness of a mouse gesture.

Thank you!
Extension rox

**Comment by smoothgesturesplus** [comment]
I don't think it can be done exactly how you describe, but I do have a similar find feature in mind. I plan to be testing it soon.

**Comment by smoothgesturesplus** [comment]
Will be in the next release
