### ISSUE TITLE
Mouse cursor jump down on right mouse button click

### ISSUE THREAD

**Issue by NickSniper** [smoothgesturesplus/Issues#43]
I use Smoothgesturesplus. After last Smoothgesturesplus and Chrome update the mouse cursor "jump" on right mouse button press. It "jump" for 5 millimetres from up to down. System: Mac OS X 10.11.5. Chrome 48.0.2564.116 (64-bit). Smooth Gestures Plus 2.1

**Comment by magicmikela** [comment]
Same here. EX: Using google sheets, if I right click on row 41, it will jump down to 42 and open the right click menu. Suppper annoying. As of today too, it jumps way more in other pages...like on Facebook it jumps about 3 inches to the right and then down half an inch. By turning this add-on off, right click went back to normal.

**Comment by thebtf** [comment]
Same here. Workaround is enable fullscreen for Chrome. Very annoying, and still not fixed. Mac OS X 10.10.5, Chrome/49.0.2623.75. SGP 2.1

**Comment by smoothgesturesplus** [comment]
This should have been fixed by the release on the 12th. Let me know if you still see an issue.
