### ISSUE TITLE
Blacklist does not appear to function.

### ISSUE THREAD

**Issue by crkochan** [smoothgesturesplus/Issues#45]
The blacklist feature does not appear to work when visiting a site that I have entered into the black list in the settings panel.

I use a site called Tinkercad to create and modify objects for 3D printing. The site make heavy use of the right mouse button to move about in the editor. If left enabled, I will inevitably trigger a mouse gesture.

The URL in question is: https://www.tinkercad.com

I've tried entering `www.tinkercad.com`, as well as shortening it to `tinkercad.com` in the blacklist input box. No matter what I enter, SM+ does not disable itself when visiting the site, and mouse gestures will still trigger. If I click the icon in the Chrome menu bar, the pop-up still states `Gestures Working`.

This behaviour is also present when blacklisting domains such as `apple.com`, and even `mail.google.com` from the example.

Expected behaviour: Gestures would not function on any domain listed in the blacklist, and the SM+ icon would state `Gestures Blocked`, or something similar.

**Comment by smoothgesturesplus** [comment]
Thanks for reporting this! It was broken and has been fixed. It should be released within the next couple days.
