### ISSUE TITLE
Smooth Gestures Plus needs to be updated?

### ISSUE THREAD

**Issue by MeszesKPT** [smoothgesturesplus/Issues#47]
First of all thank you for this great extension, that I've been using for a few years now.

Today opening Chrome v53.0 and performing the first gesture opened up a new window, telling me to checkmark Developer Mode on the extensions page then to click Update Extensions Now. I did that but seemingly nothing happened. Doing gestures just opens the same window. Restarted Chrome and PC several times, no difference.

In the past I never had to do quirks like that, Smooth Gestures updated itself automatically. Any idea what I could do to solve the issue? Thank you.

With regards,

Tamas Kiss-Pal

**Comment by evanhoo** [comment]
@MeszesKPT  I have the same problem!  An window just pops out whenever I draw a gesture. 
Here is the what it says:

> **smooth gestures PLUS needs to be Updated**
> To update smooth gestures PLUS:
> Open the Extensions Page
> Checkmark "Developer Mode"
> Click "Update Extensions Now"

Unfortunately, what it suggests won't work. I've even tried reinstalling it, still no use. 
@smoothgesturesplus  HELP!

**Comment by stresu** [comment]
Same over here (v53 Chrome and v 2.6.1 SG)...and it started being a **real** pain. Getting on my nerves already...

**Comment by byungil924** [comment]
Same problem here. I guess it started yesterday.
The function does not work even though I draw gestures.

**Comment by ryhaberecht** [comment]
Same problem for me.
Chromium Version 53.0.2785.113 Built on 8.5, running on Debian 8.6 (64-bit)

**Comment by freeride280** [comment]
How do we stop the spamming ?

**Comment by rcardenal** [comment]
Same here, both under Linux and Windows, please fix asap.

**Comment by tempura666** [comment]
Me too, on Mac 10.12. and latest Extras installed.

If not corrected THIS BUG within two or three days, I might stop the subscription :D

**Comment by ktdd** [comment]
Already canceled my subscription, this extension seems to be abandoned. No updates and developer is never around on issue tracker.

**Comment by stresu** [comment]
you're lucky...I bought the lifetime s***

**Comment by rcardenal** [comment]
crxMouse guys...

**Comment by smoothgesturesplus** [comment]
Hello! I've found the bug. It is fixed in version 2.6.2 and should be
available within the hour. You can force the update or wait a day for it to
automatically install. You should see it soon!

Scott

**Comment by bbruun** [comment]
Thank you Scott - very much appreciated being able to use Chrome again :-)

**Comment by draioncrimson** [comment]
I have the same issue. Version 2.8.9... How can I "force the update"?

**Comment by ktdd** [comment]
> I have the same issue. Version 2.8.9... How can I "force the update"?

The bug was fixed almost 4 years ago. Your problem is related to something else.

**Comment by smoothgesturesplus** [comment]
Unfortunately, Smooth Gestures Plus is not working currently. We have submitted a fix to Google, but are currently waiting on Google to approve the update.

When the update is approved it should install automatically and Smooth Gestures Plus will work again.

I expect that your license is active as will be working as soon as the update is complete.
