### ISSUE TITLE
bug: scroll to top and scroll to bottom no longer working

### ISSUE THREAD

**Issue by sinrise** [smoothgesturesplus/Issues#56]
After updating to Chrome Version 61.0.3163.79 (Official Build) (64-bit), this is no longer working. I have 'scroll to top' set to 'action button + up' and 'scroll to bottom' set to 'action button + down'.

Nothing happens when using these two gestures anymore. I tried deleting them and re-adding them but the behavior is the same. I have tried this on several different websites.

**Comment by smoothgesturesplus** [comment]
Fixed in 2.8 (being rolled out) #55
