### ISSUE TITLE
Does not work in Opera developer in ANY search engine page

### ISSUE THREAD

**Issue by mnut** [smoothgesturesplus/Issues#64]
On new Opera developer 59.0.3173.0 (Chromium 72.0.3626.14) Smooth Gestures plus stopped working on Google pages (it works everywhere else)
PS Smooth Gestures plus do not work (only on Google pages, i.e. Google search, YouTube etc) on Opera Developer 59.0.3187.0 as well - the problem appeared with Chromium 72 (it worked OK in Chromium 71) 
PS 2 - Don't bother it's not Chromium 72, it's only Opera!
PS 3 - It's either smooth gestures or opera! I cannot use both!
PS 4 - I changed the search engine in Bing, duckduckgo etc - smooth gestures is not working in any of the search engines pages!

**Comment by mtakala** [comment]
I have this same issue; the google search results page somehow makes the extension to not work in Opera anymore. Please try to debug this issue.

**Comment by mnut** [comment]
This bug goes back to December 2018, i.e. a year ago. Will you solve the problem? Smooth gestures does not work in any search engine's page and, also, in anything under the google domain (including gmail). Please correct it!

**Comment by mtakala** [comment]
Opera has added an option to allow extension to access search page results. This can be changed from the list of extensions and checked/unchecked per extension.

**Comment by mnut** [comment]
Thanks a lot! That's it! Problem solved!


On Wed, 04 Dec 2019 14:31:00 +0200, mtakala <notifications@github.com>  
wrote:

>
> Opera has added an option to allow extension to access search page  
> results. This can be changed from the list of extensions and  
> >checked/unchecked per extension.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

---------
Th. Ds.
