### ISSUE TITLE
Disable Smooth Gestures for a specific website

### ISSUE THREAD

**Issue by hikinandbikin** [smoothgesturesplus/Issues#70]
First, I love smooth gestures. 
There are a few occasions where I would like to disable smooth gestures for a particular sight. Pages that use the right click for other advanced features, like tinkercad for instance uses right click for perspective changes. Some game sites right as well. It seems like a there used to be a button to disable the extension on a given page, but I don't see that feature. 
If there is already an easy method let me know. If not it would be great to add a menu option to in the chrome icon to not run smooth gestures on this page...
Thanks

**Comment by smoothgesturesplus** [comment]
I think we have the solution for you: Checkout the blacklist in settings.

**Comment by hikinandbikin** [comment]
Thanks, worked perfectly.
