### ISSUE TITLE
Extension requires an update but is on latest version in Chrome Webstore

### ISSUE THREAD

**Issue by bradarv90** [smoothgesturesplus/Issues#76]
I'm currently unable to use the extension. Whenever I use any gesture, a popup shows telling me to update the extension. I'm seeing that I'm running 2.8.9 and that the latest version in Chrome is also 2.8.9. 

Chrome version: 80.0.3987.163

I've been using this extension for years, so I have no idea what the issue could be. Let me know how I can help you debug.

**Comment by vestmon** [comment]
Same problem just occurred.  Reboot is no help.

**Comment by bradarv90** [comment]
I also just switched to my Mac. This issue appears to be related to the latest version of Chrome. This extension was working until I updated Chrome. My Mac's version is 81.0.4044.113.

**Comment by FredrikGullberg** [comment]
I'm also having this problem, Chrome 80.0.3987.116

**Comment by stresu** [comment]
Same here...not working anymore on Chrome 81.0.4044.113 (Official Build) (64-bit) no matter what.

**Comment by abatrakov** [comment]
The same for me. Not working with last Chrome and asking for an update.

**Comment by mulder21c** [comment]
I'm having this problem too, Chrome 81.0.4044.113 on Windows 10

**Comment by draioncrimson** [comment]
Same problem. Chrome 81.0.4044.113 (Official Build) (64-bit). I have an active license and I've been using gestures for so long that it feels like one of my mouse buttons is missing now...

**Comment by HstsuneMiku** [comment]
same problem 
版本 80.0.3987.100（正式版本） （64 位）

**Comment by jharveytx** [comment]
Ditto - Same problem.

**Comment by smoothgesturesplus** [comment]
Unfortunately, Smooth Gestures Plus is not working currently. We have submitted a fix to Google, but are currently waiting on Google to approve the update.

When the update is approved it should install automatically and Smooth Gestures Plus will work again.

I expect that your license is active as will be working as soon as the update is complete.

**Comment by bodahl** [comment]
Same here. Hope the update is approved quickly...

**Comment by bradarv90** [comment]
I just updated and we're back to working again. Thank you for resolving the issue so quickly!

**Comment by vestmon** [comment]
Woohoo! It works now.  Thanks, Scott.

**Comment by smoothgesturesplus** [comment]
Confirmed! Up and running.
